export interface ListingItem {
  id: number;
  city: 'Красноярск' | 'Москва' | 'Санкт-Петербург' | string;
  title: string;
  deal_type: 'rent' | 'buy';
  source: 'cian' | 'yandex' | 'avito' | 'domclick' | 'landlord';
  price_rub: number;
  rooms_count: number;
  area_sqm: number;
  floor: number;
  total_floors: number;
  address: string;
  district_name: string;
  landmarks: string[];
  latitude: number;
  longitude: number;
  nearest_school: string;
  school_walk_minutes: number;
  safety_score: number;
  photos: string[];
  description: string;
  ai_summary: string;
  ai_tags: string[];
  transport_info: string;
  cadastral_number?: string;
  accessibility_info?: string;
  verified_sources: string[];
  created_at: string;
}

export interface FriendProfile {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  budget_max: number;
  preferred_districts: string[];
  likedListingIds: number[];
}

export interface UserMatch {
  listingId: number;
  matchedWith: FriendProfile[];
  timestamp: string;
}

// ----------------- КРАСНОЯРСК -----------------
export const krasnoyarskListings: ListingItem[] = [
  {
    id: 101,
    city: 'Красноярск',
    title: '1-к квартира 38 м² у Школы №150 на Взлётке',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 35000,
    rooms_count: 1,
    area_sqm: 38.5,
    floor: 6,
    total_floors: 10,
    address: 'г. Красноярск, ул. 78 Добровольческой Бригады, 15',
    district_name: 'Советский р-н (Взлётка)',
    landmarks: ['ТРЦ Планета', 'парк 400-летия Красноярска', 'Взлётка', 'Арена Север'],
    latitude: 56.0465,
    longitude: 92.9095,
    nearest_school: 'МАОУ Школа № 150 с углубленным изучением предметов',
    school_walk_minutes: 3,
    safety_score: 9.2,
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
    description: 'Светлая однушка в сердце Взлётки. Школа №150 прямо во дворе без перехода дорог. В шаговой доступности ТРЦ Планета, парк 400-летия Красноярска. Чистый подъезд, консьерж.',
    ai_summary: 'Топовая локация Взлётки: аренда 35 000 ₽/мес, школа №150 в 3 минутах пешком, высокая безопасность 9.2/10.',
    ai_tags: ['школа №150 во дворе', 'ТРЦ Планета', 'Взлётка', 'безопасный двор'],
    transport_info: 'Остановка «ТРЦ Планета», автобусы во все районы',
    cadastral_number: '24:50:0400032:142',
    accessibility_info: 'Доступная среда: пандус с поручнем, лифт грузопассажирский (zhit-vmeste.ru)',
    verified_sources: ['Циан', 'Яндекс.Недвижимость', 'НСПД Росреестр', '2ГИС'],
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 102,
    city: 'Красноярск',
    title: '2-к квартира 56 м² рядом со школой №149 в ЖК «Скандис»',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 39000,
    rooms_count: 2,
    area_sqm: 56.0,
    floor: 4,
    total_floors: 14,
    address: 'г. Красноярск, ул. Молокова, 1к1',
    district_name: 'Советский р-н (Взлётка)',
    landmarks: ['ЖК Скандис', 'ул. Молокова', 'Взлётка-Плаза'],
    latitude: 56.0442,
    longitude: 92.9150,
    nearest_school: 'Средняя школа № 149 с углубленным обучением',
    school_walk_minutes: 4,
    safety_score: 9.4,
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    description: 'Уютная двухкомнатная квартира в популярном кирпичном микрорайоне Скандис. Закрытый двор без машин, ландшафтный парк внутри двора. Рядом школа №149 и детский сад.',
    ai_summary: 'Идеально для семьи или совместного съема: 2 комнаты за 39 000 ₽, закрытый безопасный двор ЖК Скандис, школа в 4 мин.',
    ai_tags: ['ЖК Скандис', 'двор без машин', '2 комнаты', 'школа №149'],
    transport_info: 'Остановка «Городок», 10 мин до Октябрьского моста',
    cadastral_number: '24:50:0400038:512',
    accessibility_info: 'Беспрепятственный вход с уровня тротуара, широкие входные группы',
    verified_sources: ['Яндекс.Недвижимость', '2ГИС', 'НСПД', 'ФППД'],
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 103,
    city: 'Красноярск',
    title: '1-к квартира 42 м² у Школы №154 в ЖК «Преображенский»',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 37000,
    rooms_count: 1,
    area_sqm: 42.0,
    floor: 8,
    total_floors: 24,
    address: 'г. Красноярск, ул. Авиаторов, 41',
    district_name: 'Советский р-н (Преображенский)',
    landmarks: ['ЖК Преображенский', 'ул. Авиаторов', 'ТРЦ Планета'],
    latitude: 56.0520,
    longitude: 92.9180,
    nearest_school: 'Новая школа № 154 (по нацпроекту "Образование")',
    school_walk_minutes: 3,
    safety_score: 9.3,
    photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80'],
    description: 'Монолитно-кирпичный дом комфорт-класса. Свежий евроремонт, гардеробная. Новейшая школа №154 с бассейном и стадионом в 200 метрах.',
    ai_summary: 'Новый жилой комплекс, ультрасовременная школа №154 в 3 мин ходьбы, аренда 37 000 ₽.',
    ai_tags: ['ЖК Преображенский', 'школа с бассейном', 'до 40к', 'новый ремонт'],
    transport_info: 'Остановка «Детский центр», выезд на Северное шоссе',
    cadastral_number: '24:50:0400041:882',
    accessibility_info: 'Оборудован подъемником для МГН и тактильной плиткой',
    verified_sources: ['Циан', 'НСПД', '2ГИС'],
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 104,
    city: 'Красноярск',
    title: '1-к квартира 36 м² в Академгородке у Гимназии №13',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 32000,
    rooms_count: 1,
    area_sqm: 36.0,
    floor: 5,
    total_floors: 9,
    address: 'г. Красноярск, Академгородок, 24',
    district_name: 'Октябрьский р-н (Академгородок)',
    landmarks: ['Красивый берег', 'Гимназия №13', 'Институт физики СО РАН', 'сосновый бор'],
    latitude: 55.9915,
    longitude: 92.7680,
    nearest_school: 'МАОУ Гимназия № 13 «Академ» (ТОП-5 края)',
    school_walk_minutes: 2,
    safety_score: 9.6,
    photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'],
    description: 'Самый экологически чистый район Красноярска! Роза ветров, сосновый бор, смотровая площадка Красивый берег на Енисее. Престижнейшая гимназия №13 в 2 минутах от подъезда.',
    ai_summary: 'Лучшая экология и сильнейшая гимназия №13. Бюджетная аренда 32 000 ₽ в сосновом бору.',
    ai_tags: ['чистый воздух', 'Гимназия №13', 'сосновый бор', 'топ безопасность'],
    transport_info: 'Остановка «Академгородок», автобусы №83, 63, 2',
    cadastral_number: '24:50:0100014:321',
    accessibility_info: 'Пологий пандус, тихая парковая пешеходная зона',
    verified_sources: ['Яндекс.Недвижимость', '2ГИС', 'Росстат'],
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 105,
    city: 'Красноярск',
    title: '2-к квартира 50 м² рядом со школой №151 на Алексеева',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 38000,
    rooms_count: 2,
    area_sqm: 50.0,
    floor: 7,
    total_floors: 10,
    address: 'г. Красноярск, ул. Алексеева, 49',
    district_name: 'Советский р-н (Взлётка)',
    landmarks: ['ТК Командор', 'ТРЦ Планета', 'ул. Алексеева'],
    latitude: 56.0545,
    longitude: 92.9020,
    nearest_school: 'МАОУ Школа № 151',
    school_walk_minutes: 4,
    safety_score: 9.0,
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80'],
    description: 'Просторная двухкомнатная квартира для семьи или совместного проживания. Раздельные комнаты, большая застекленная лоджия. Школа №151 и детский сад прямо во дворе.',
    ai_summary: '2 комнаты за 38 000 ₽ на ул. Алексеева, школа №151 в 4 минутах без опасных дорог.',
    ai_tags: ['2-к квартира', 'школа №151', 'Взлётка', 'семейная'],
    transport_info: 'Остановка «ТК Командор», удобная развязка',
    cadastral_number: '24:50:0400030:771',
    accessibility_info: 'Оснащен пандусом у подъезда',
    verified_sources: ['Циан', '2ГИС'],
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: 106,
    city: 'Красноярск',
    title: '1-к студия 34 м² у Гимназии №2 в историческом Центре',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 38000,
    rooms_count: 1,
    area_sqm: 34.0,
    floor: 3,
    total_floors: 5,
    address: 'г. Красноярск, пр. Мира, 85',
    district_name: 'Центральный р-н (Центр)',
    landmarks: ['пр. Мира', 'Театр Пушкина', 'набережная Енисея', 'Центральный парк'],
    latitude: 56.0125,
    longitude: 92.8680,
    nearest_school: 'МАОУ Гимназия № 2 (Центр)',
    school_walk_minutes: 3,
    safety_score: 9.1,
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
    description: 'Исторический центр, тихий зеленый закрытый двор со шлагбаумом. Потолки 3 метра. В двух шагах проспект Мира, Гимназия №2, театры и набережная Енисея.',
    ai_summary: 'Престижный центр города за 38 000 ₽, рейтинговая Гимназия №2 в 3 мин.',
    ai_tags: ['Центр', 'пр. Мира', 'Гимназия №2', 'высокие потолки'],
    transport_info: 'Остановка «Театр Пушкина», центр транспортных артерий',
    cadastral_number: '24:50:0300102:44',
    accessibility_info: 'Классический кирпичный дом, пологий въезд во двор',
    verified_sources: ['Циан', 'Яндекс.Карты', 'НСПД'],
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 107,
    city: 'Красноярск',
    title: '1-к квартира 37 м² у Школы №158 на набережной (Белые Росы)',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 30000,
    rooms_count: 1,
    area_sqm: 37.0,
    floor: 12,
    total_floors: 24,
    address: 'г. Красноярск, ул. Карамзина, 18',
    district_name: 'Свердловский р-н (Пашенный)',
    landmarks: ['Белые Росы', 'Ярыгинская набережная', 'остров Отдыха'],
    latitude: 55.9920,
    longitude: 92.8680,
    nearest_school: 'Школа № 158 «Графика» на набережной Енисея',
    school_walk_minutes: 4,
    safety_score: 8.9,
    photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'],
    description: 'Видовая квартира на Енисей и Ярыгинскую набережную. Новая ультрасовременная школа №158 Графика в 4 минутах ходьбы. Прогулочные зоны, эко-тропы.',
    ai_summary: 'Вид на Енисей, школа №158 на набережной, доступная аренда 30 000 ₽.',
    ai_tags: ['набережная Енисея', 'Белые Росы', 'школа Графика', 'видовая'],
    transport_info: 'Остановка «Белые росы», 7 мин до Коммунального моста',
    cadastral_number: '24:50:0700021:119',
    accessibility_info: 'Безбарьерная среда в подъезде, 2 скоростных лифта',
    verified_sources: ['Яндекс.Недвижимость', '2ГИС', 'data.gov.ru'],
    created_at: new Date(Date.now() - 3600000 * 25).toISOString(),
  },
  {
    id: 108,
    city: 'Красноярск',
    title: '2-к в новостройке ЖК «Арбан Smart» 48 м² (Покупка)',
    deal_type: 'buy',
    source: 'cian',
    price_rub: 7800000,
    rooms_count: 2,
    area_sqm: 48.0,
    floor: 9,
    total_floors: 17,
    address: 'г. Красноярск, ул. Шахтеров, 40',
    district_name: 'Центральный р-н (мкрн Покровский)',
    landmarks: ['мкрн Покровский', 'ул. Шахтеров', 'ТРЦ Покровский'],
    latitude: 56.0350,
    longitude: 92.8850,
    nearest_school: 'Школа № 153',
    school_walk_minutes: 5,
    safety_score: 9.1,
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
    description: 'Покупка квартиры от надежного застройщика Арбан. Кирпичные стены 90 см, подземный паркинг, консьерж-сервис, французские окна. Подходит под Семейную ипотеку 6%.',
    ai_summary: 'Покупка в кирпичном ЖК от Арбан. Льготная ипотека 6%, школа рядом.',
    ai_tags: ['покупка', 'Арбан', 'семейная ипотека 6%', 'кирпич'],
    transport_info: 'Остановка «Улица Шахтеров»',
    cadastral_number: '24:50:0300155:92',
    accessibility_info: 'Консьерж, подъемник для инвалидов, подземный паркинг',
    verified_sources: ['Циан', 'НСПД', 'Росреестр'],
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
  }
];

// ----------------- МОСКВА -----------------
export const moscowListings: ListingItem[] = [
  {
    id: 201,
    city: 'Москва',
    title: '1-к квартира 40 м² у Шуваловской гимназии (Раменки)',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 48000,
    rooms_count: 1,
    area_sqm: 40.0,
    floor: 7,
    total_floors: 16,
    address: 'г. Москва, Мичуринский проспект, 16',
    district_name: 'Раменки (ЗАО)',
    landmarks: ['МГУ', 'Воробьевы горы', 'парк Олимпийской деревни', 'Мичуринский проспект'],
    latitude: 55.7015,
    longitude: 37.5020,
    nearest_school: 'ГБОУ Школа № 1448 (Шуваловская гимназия)',
    school_walk_minutes: 4,
    safety_score: 9.5,
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
    description: 'Светлая квартира в престижном районе Раменки. Рядом Шуваловская гимназия и главное здание МГУ. 5 минут пешком до метро Раменки. Зеленый двор, консьерж.',
    ai_summary: 'Престижные Раменки: Шуваловская гимназия в 4 минутах, эко-лидер ЗАО Москвы, безопасность 9.5/10.',
    ai_tags: ['Раменки', 'МГУ', 'Шуваловская гимназия', 'эко-район'],
    transport_info: 'м. Раменки (5 мин пешком), м. Мичуринский проспект (БКЛ)',
    cadastral_number: '77:07:0012001:542',
    accessibility_info: 'Пандус с ограждением, вход без ступеней, лифт ОТИС (zhit-vmeste.ru)',
    verified_sources: ['Циан', 'Яндекс.Недвижимость', 'НСПД', 'data.mos.ru'],
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 202,
    city: 'Москва',
    title: '2-к квартира 58 м² в Хамовниках у Лицея №1535',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 75000,
    rooms_count: 2,
    area_sqm: 58.0,
    floor: 4,
    total_floors: 9,
    address: 'г. Москва, ул. Усачёва, 29к1',
    district_name: 'Хамовники (ЦАО)',
    landmarks: ['Усачёвский рынок', 'Лицей 1535', 'Лужники', 'Парк Новодевичьи пруды'],
    latitude: 55.7270,
    longitude: 37.5680,
    nearest_school: 'Лицей № 1535 (ТОП-1 школа России по рейтингу RAEX)',
    school_walk_minutes: 3,
    safety_score: 9.7,
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    description: 'Хамовники — золотой стандарт комфорта столицы. Легендарный лицей №1535 в 200 метрах. Закрытый тихий двор, кирпичный фасад, высокие потолки.',
    ai_summary: 'Топовое образование страны (Лицей 1535), безопасность 9.7/10, рядом Усачевский рынок и Лужники.',
    ai_tags: ['Хамовники', 'Лицей 1535', 'ЦАО', 'топ безопасность'],
    transport_info: 'м. Спортивная (4 мин пешком), МЦК Лужники',
    cadastral_number: '77:01:0005012:118',
    accessibility_info: 'Оборудован подъемной платформой, широкие проемы по СП 42.13330',
    verified_sources: ['Яндекс.Недвижимость', 'Циан', 'Росреестр', '2ГИС'],
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 203,
    city: 'Москва',
    title: '2-к квартира 54 м² на Пресне рядом с Москва-Сити',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 68000,
    rooms_count: 2,
    area_sqm: 54.0,
    floor: 6,
    total_floors: 14,
    address: 'г. Москва, Шмитовский проезд, 19',
    district_name: 'Пресненский (ЦАО)',
    landmarks: ['Москва-Сити', 'Парк Красная Пресня', 'ул. 1905 года', 'Шмитовский'],
    latitude: 55.7560,
    longitude: 37.5450,
    nearest_school: 'ГБОУ Романовская школа (бывш. №1240)',
    school_walk_minutes: 5,
    safety_score: 9.2,
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80'],
    description: 'Пресненский район, 10 минут пешком до башен Сити и парка Красная Пресня. Отличная квартира для совместного проживания. Раздельные комнаты, дизайнерский ремонт.',
    ai_summary: 'Пресня у Сити: быстрый доступ к деловому центру, рейтинговые школы и парки.',
    ai_tags: ['Пресня', 'Москва-Сити', 'Шмитовский', '2 комнаты'],
    transport_info: 'м. Улица 1905 года (7 мин), м. Шелепиха',
    cadastral_number: '77:01:0004022:319',
    accessibility_info: 'Пандус на крыльце, доступная входная группа',
    verified_sources: ['Циан', '2ГИС', 'НСПД'],
    created_at: new Date(Date.now() - 3600000 * 9).toISOString(),
  },
  {
    id: 204,
    city: 'Москва',
    title: '1-к квартира 38 м² у метро Проспект Вернадского',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 42000,
    rooms_count: 1,
    area_sqm: 38.0,
    floor: 5,
    total_floors: 12,
    address: 'г. Москва, ул. Удальцова, 23',
    district_name: 'Проспект Вернадского (ЗАО)',
    landmarks: ['Лицей 1514', 'Удальцовские пруды', 'парк 50-летия Октября', 'БКЛ'],
    latitude: 55.6840,
    longitude: 37.5090,
    nearest_school: 'Лицей № 1514 (ТОП-3 школ Москвы)',
    school_walk_minutes: 4,
    safety_score: 9.3,
    photos: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80'],
    description: 'Зеленый интеллигентный район Юго-Запада. В шаговой доступности знаменитый лицей №1514, Удальцовские пруды и станция БКЛ.',
    ai_summary: 'Лучший баланс цены и качества: 42 000 ₽, легендарный Лицей 1514 в 4 мин, парк во дворе.',
    ai_tags: ['Лицей 1514', 'Проспект Вернадского', 'БКЛ', 'пруды'],
    transport_info: 'м. Проспект Вернадского (БКЛ и Сокольническая линия, 4 мин)',
    cadastral_number: '77:07:0014002:88',
    accessibility_info: 'Пандус в подъезде, безбарьерная среда',
    verified_sources: ['Циан', 'Яндекс.Недвижимость', 'data.gov.ru'],
    created_at: new Date(Date.now() - 3600000 * 15).toISOString(),
  },
  {
    id: 205,
    city: 'Москва',
    title: '2-к квартира в новостройке ЖК «Матвеевский парк» 53 м² (Покупка)',
    deal_type: 'buy',
    source: 'cian',
    price_rub: 13200000,
    rooms_count: 2,
    area_sqm: 53.0,
    floor: 10,
    total_floors: 33,
    address: 'г. Москва, Очаковское шоссе, вл. 3',
    district_name: 'Очаково-Матвеевское (ЗАО)',
    landmarks: ['ЖК Матвеевский парк', 'м. Аминьевская', 'МЦД-4 Аминьевская'],
    latitude: 55.6980,
    longitude: 37.4650,
    nearest_school: 'Новая школа на 1150 мест во дворе ЖК',
    school_walk_minutes: 2,
    safety_score: 9.0,
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
    description: 'Новый монолитный дом от ПИК. Сдача 2026 г., эскроу-счет. Подходит под Семейную ипотеку 6% и IT-ипотеку. Школа и детский сад прямо на территории квартала.',
    ai_summary: 'Покупка по Семейной ипотеке 6% в ЗАО. Школа во дворе, метро Аминьевская 5 мин.',
    ai_tags: ['покупка', 'Семейная ипотека 6%', 'ЖК Матвеевский парк', 'школа во дворе'],
    transport_info: 'м. Аминьевская (БКЛ) и МЦД-4 (5 мин пешком)',
    cadastral_number: '77:07:0013008:1204',
    accessibility_info: 'Современный вход на уровне земли, скоростные лифты',
    verified_sources: ['Циан', 'НСПД', 'ЕИСЖС наш.дом.рф'],
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
  }
];

// ----------------- САНКТ-ПЕТЕРБУРГ -----------------
export const spbListings: ListingItem[] = [
  {
    id: 301,
    city: 'Санкт-Петербург',
    title: '1-к квартира 42 м² на Петроградке у Гимназии №610',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 39000,
    rooms_count: 1,
    area_sqm: 42.0,
    floor: 3,
    total_floors: 6,
    address: 'г. Санкт-Петербург, Малый проспект П.С., 40',
    district_name: 'Петроградский район (Петроградка)',
    landmarks: ['Петроградка', 'м. Чкаловская', 'Гимназия 610', 'Большой проспект'],
    latitude: 59.9590,
    longitude: 30.2980,
    nearest_school: 'Классическая гимназия № 610 (ТОП-3 школ СПб)',
    school_walk_minutes: 3,
    safety_score: 9.4,
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
    description: 'Петроградская сторона. Исторический доходный дом после капремонта. Высокие потолки 3.2 м, паркет. Гимназия №610 в 250 метрах. До метро Чкаловская 5 минут.',
    ai_summary: 'Культурное сердце Петербурга: аренда 39 000 ₽ на Петроградке, знаменитая Гимназия №610 в 3 мин.',
    ai_tags: ['Петроградка', 'Гимназия 610', 'высокие потолки', 'до 40к'],
    transport_info: 'м. Чкаловская (5 мин пешком), м. Спортивная',
    cadastral_number: '78:32:0001024:118',
    accessibility_info: 'Пологий въезд в арку, домофон, чистая парадная',
    verified_sources: ['Циан', 'Яндекс.Недвижимость', '2ГИС', 'НСПД'],
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 302,
    city: 'Санкт-Петербург',
    title: '2-к квартира 55 м² у метро Комендантский проспект',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 38000,
    rooms_count: 2,
    area_sqm: 55.0,
    floor: 7,
    total_floors: 16,
    address: 'г. Санкт-Петербург, Комендантский проспект, 17к1',
    district_name: 'Приморский район',
    landmarks: ['Комендантский проспект', 'Юнтоловский лесопарк', 'ТРК Променад'],
    latitude: 60.0110,
    longitude: 30.2580,
    nearest_school: 'Гимназия № 540 с инженерно-технологическим уклоном',
    school_walk_minutes: 4,
    safety_score: 9.2,
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    description: 'Приморский район — лидер по популярности среди семей. Двухкомнатная квартира с изолированными комнатами. Новая гимназия №540 во дворе.',
    ai_summary: 'Отличная двушка для совместного проживания: 38 000 ₽, Приморский район, гимназия 540 в 4 мин.',
    ai_tags: ['Приморский район', 'Комендантский', '2 комнаты', 'до 40к'],
    transport_info: 'м. Комендантский проспект (6 мин пешком)',
    cadastral_number: '78:34:0004112:504',
    accessibility_info: 'Пандус с поручнями у входа, грузовой лифт',
    verified_sources: ['Яндекс.Недвижимость', 'Циан', '2ГИС'],
    created_at: new Date(Date.now() - 3600000 * 7).toISOString(),
  },
  {
    id: 303,
    city: 'Санкт-Петербург',
    title: '1-к квартира 39 м² на Васильевском острове у СПбГУ',
    deal_type: 'rent',
    source: 'cian',
    price_rub: 37000,
    rooms_count: 1,
    area_sqm: 39.0,
    floor: 4,
    total_floors: 9,
    address: 'г. Санкт-Петербург, Средний проспект В.О., 55',
    district_name: 'Василеостровский район (В.О.)',
    landmarks: ['Васильевский остров', 'м. Василеостровская', 'СПбГУ', 'Севкабель Порт'],
    latitude: 59.9380,
    longitude: 30.2720,
    nearest_school: 'Академическая гимназия № 56',
    school_walk_minutes: 5,
    safety_score: 9.3,
    photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'],
    description: 'Васильевский остров. Рядом набережная, Севкабель Порт, университетский кластер. Тихий двор, чистая парадная, свежий ремонт.',
    ai_summary: 'Атмосферный Васильевский остров: 37 000 ₽, школы и университеты рядом, 7 мин до метро.',
    ai_tags: ['Васильевский остров', 'Средний проспект', 'СПбГУ', 'уютная'],
    transport_info: 'м. Василеостровская (7 мин пешком), удобный выезд на ЗСД',
    cadastral_number: '78:06:0002015:32',
    accessibility_info: 'Оборудован пандусом на крыльце',
    verified_sources: ['Циан', 'Яндекс.Карты', 'НСПД'],
    created_at: new Date(Date.now() - 3600000 * 11).toISOString(),
  },
  {
    id: 304,
    city: 'Санкт-Петербург',
    title: '2-к квартира 56 м² у Парка Победы в Московском районе',
    deal_type: 'rent',
    source: 'yandex',
    price_rub: 44000,
    rooms_count: 2,
    area_sqm: 56.0,
    floor: 5,
    total_floors: 10,
    address: 'г. Санкт-Петербург, Московский проспект, 172',
    district_name: 'Московский район',
    landmarks: ['Парк Победы', 'Московский проспект', 'СКК', 'аэропорт Пулково'],
    latitude: 59.8690,
    longitude: 30.3210,
    nearest_school: 'Физико-математический лицей № 366 (ТОП-5)',
    school_walk_minutes: 4,
    safety_score: 9.5,
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80'],
    description: 'Сталинский ампир в престижном Московском районе. Напротив Парк Победы. Сильнейший физмат лицей №366 в 300 метрах. Идеально для двоих друзей или семьи.',
    ai_summary: 'Престижный Московский проспект: Парк Победы через дорогу, ФМЛ 366 в 4 мин, безопасность 9.5.',
    ai_tags: ['Московский район', 'Парк Победы', 'Лицей 366', 'сталинка'],
    transport_info: 'м. Парк Победы (4 мин пешком)',
    cadastral_number: '78:14:0007201:89',
    accessibility_info: 'Широкие марши, удобный пандус во внутреннем дворе',
    verified_sources: ['Яндекс.Недвижимость', 'Циан', '2ГИС', 'data.gov.ru'],
    created_at: new Date(Date.now() - 3600000 * 16).toISOString(),
  }
];

// All initial listings across supported cities
export const initialListings: ListingItem[] = [
  ...krasnoyarskListings,
  ...moscowListings,
  ...spbListings,
];

// Mock friends for Co-living Tinder matching
export const initialFriends: FriendProfile[] = [
  {
    id: 'friend-artem',
    name: 'Артём',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: 'Ищу соседа на длительный срок. Люблю порядок, работаю в IT на удаленке. В приоритете Взлётка или Петроградка.',
    budget_max: 40000,
    preferred_districts: ['Взлётка', 'Петроградский район', 'Раменки'],
    likedListingIds: [101, 102, 301, 201], // Pre-liked
  },
  {
    id: 'friend-sofia',
    name: 'София',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    bio: 'Студентка магистратуры. Ищу квартиру рядом с хорошей школой/гимназией и зеленым парком. Рассматриваю Красноярск и СПб.',
    budget_max: 38000,
    preferred_districts: ['Академгородок', 'Приморский район', 'Центральный'],
    likedListingIds: [102, 104, 302, 106],
  },
  {
    id: 'friend-daniil',
    name: 'Даниил',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'Инженер-проектировщик. Важна транспортная доступность и тишина вечером. Люблю современные ЖК.',
    budget_max: 42000,
    preferred_districts: ['Советский р-н', 'Пресненский', 'Московский район'],
    likedListingIds: [101, 103, 203, 304],
  }
];
